### ISSUE TITLE
Question: how can BinaryUUID be used in a Where condition?

### ISSUE THREAD

**Issue by mbigatti** [dipeshdulal/binary-uuid-gorm#1]
How can `BinaryUUID` be used in a Where condition, for example in the following:
`res := database.DBConn.Find(&model, "UUID = ?", uuid)`

Thanks!
MB

**Comment by dipeshdulal** [comment]
@mbigatti Because binary uuid has scanner valuer interface of gorm implemented [here](https://github.com/dipeshdulal/binary-uuid-gorm/blob/master/binary_uuid.go#L50) and [here](https://github.com/dipeshdulal/binary-uuid-gorm/blob/master/binary_uuid.go#L43) I think binary uuid can be used in any statement  for gorm. 

> ow can BinaryUUID be used in a Where condition, for example in the following:
`res := database.DBConn.Find(&model, "UUID = ?", uuid)`

Your code should also work. :+1: 

```go
model := Test{}
id := uuid.MustParse("ed67a4b2-8f77-4d18-8c58-0508e7b207e8")
db.Find(&model, "id = ?", BinaryUUID(id))

log.Printf("data: %+v\n", model)
```

**Comment by dipeshdulal** [comment]
I have added ParseUUID function and some examples in readme. :bow:

**Comment by mbigatti** [comment]
Many Thanks!
